// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAygnZqHaKWDwpRnCoE4RuCqohG-bLQTqk',
    appId: '1:796849240847:web:7d8c22c0a5151b86891c7a',
    messagingSenderId: '796849240847',
    projectId: 'crypto-academy-91213',
    authDomain: 'crypto-academy-91213.firebaseapp.com',
    storageBucket: 'crypto-academy-91213.firebasestorage.app',
    measurementId: 'G-1YZRX91SYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZFxvNIBrOtW6jfP98bB3ASv_hAot_re8',
    appId: '1:796849240847:android:e4251d9bd5542b75891c7a',
    messagingSenderId: '796849240847',
    projectId: 'crypto-academy-91213',
    storageBucket: 'crypto-academy-91213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxMb_LjsIpxQU7XkH8WOzmDZIvHtNuh5U',
    appId: '1:796849240847:ios:ef74bd48f0b9c7fb891c7a',
    messagingSenderId: '796849240847',
    projectId: 'crypto-academy-91213',
    storageBucket: 'crypto-academy-91213.firebasestorage.app',
    iosClientId: '796849240847-9a5s4dd0ip9pkc31pdrfr8ae8an7ihag.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxMb_LjsIpxQU7XkH8WOzmDZIvHtNuh5U',
    appId: '1:796849240847:ios:ef74bd48f0b9c7fb891c7a',
    messagingSenderId: '796849240847',
    projectId: 'crypto-academy-91213',
    storageBucket: 'crypto-academy-91213.firebasestorage.app',
    iosClientId: '796849240847-9a5s4dd0ip9pkc31pdrfr8ae8an7ihag.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAygnZqHaKWDwpRnCoE4RuCqohG-bLQTqk',
    appId: '1:796849240847:web:a56fc5bd633e67af891c7a',
    messagingSenderId: '796849240847',
    projectId: 'crypto-academy-91213',
    authDomain: 'crypto-academy-91213.firebaseapp.com',
    storageBucket: 'crypto-academy-91213.firebasestorage.app',
    measurementId: 'G-VC35LBR5XE',
  );

}